### ISSUE TITLE
Vx Vy calculations in EKFPredict

### ISSUE THREAD

**Issue by afatsum93** [priseborough/3_state_filter#3]
Hello,

I want to ask you the question about planar motion kinematics that you have used. 
In the code it is stated that (Line 29-33)
dvx = 0.5 * dt * (ax_prev + ax_current);
Vx  = Vx + dvx;

dvy = 0.5 * dt * (ay_prev + ay_current);
Vy  = Vy + dvy;

BUT, this format assumes that YawRate is zero.

With non zero yaw rate, I would like to have your confirmation that these equations become in general planar motion:

Vxdot=0.5 * (ax_prev + ax_current)  -  0.5 * (YawRate_prev+Yawrate_Current) * Vy;
Vxdot=0.5 * (ay_prev + ay_current)  + 0.5 * (YawRate_prev+Yawrate_Current) * Vx;

Vx=Vx+Vxdot * dt;
Vy=Vy+Vydot * dt;

Regards

**Comment by priseborough** [comment]
ax and ay are specific forces in body frame (as measured by accelerometers) not velocity derivatives. Hence no correction for centripetal acceleration is required.
